version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app # Mount app directory for live updates
      - ./requirements.txt:/code/requirements.txt # Mount requirements for updates
    ports:
      - "8181:8181" # Map application port
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - ENV_FILE=.env # Load environment variables
    command: uvicorn app.main:app --host 0.0.0.0 --port 8181 --reload
